const fr = {
  nav: { prod: "Plateforme", ai: "IA", price: "Tarifs", contact: "Contact", login: "Connexion", start: "Créer une réunion" },
  hero: { badge: "Infrastructure nouvelle génération", t1: "Communication mondiale.", t2: "Sans barrière linguistique.", sub: "La plateforme SaaS qui permet à vos équipes de se comprendre instantanément. Chacun parle sa langue maternelle.", cta1: "Créer une réunion", cta2: "Découvrir les offres" },
  social: { title: "Conçu pour les standards internationaux", m1_val: "5.5 Mds", m1_lbl: "de non-anglophones", m2_val: "1080p", m2_lbl: "Qualité vidéo HD native", m3_val: "50ms", m3_lbl: "Latence mondiale garantie", m4_val: "E2EE", m4_lbl: "Chiffrement de bout en bout" },
  problem: { tag: "L'enjeu global", title: "La barrière linguistique détruit la productivité.", desc: "Le monde des affaires est global, mais la communication ne l'est pas. Les entreprises perdent un temps critique en malentendus.", p1: "Visioconférence unifiée HD", p2: "Traduction vocale instantanée", p3: "Sécurité et souveraineté" },
  ai: { title: "Mettez la puissance de l'IA au service de vos réunions.", sub: "Exploitez pleinement chaque appel. L'intelligence artificielle documente et optimise vos échanges.", f1_title: "Prise de notes en direct", f1_desc: "L'IA rédige les minutes, identifie les décisions et assigne les tâches.", f2_title: "Résumé automatisé", f2_desc: "Un résumé traduit est envoyé par email à tous les participants.", f3_title: "Amélioration Studio", f3_desc: "Suppression du bruit et sous-titres traduits incrustés." },
  integrations: { title: "S'intègre parfaitement à votre écosystème" },
  segments: { b2b_title: "Entreprises (B2B)", b2b_desc: "Unifiez votre communication mondiale et réduisez vos coûts d'infrastructure.", b2b_cta: "Voir les plans équipe →", b2g_title: "Institutions (B2G)", b2g_desc: "Souveraineté des données, déploiement sur-mesure et conformité stricte.", b2g_cta: "Contacter les ventes →", b2c_title: "Utilisateurs (B2C)", b2c_desc: "Collaborez avec vos clients étrangers sans aucune friction linguistique.", b2c_cta: "Démarrer gratuitement →" },
  final: { title: "Prêt à transformer vos réunions ?", cta1: "Créer une réunion", cta2: "Contacter l'équipe" },
  pricing: { title: "Investissez dans la clarté.", sub: "Déployez l'infrastructure la plus avancée. Essayez gratuitement pendant 3 jours.", b2c_title: "Premium", b2c_desc: "Pour les freelances internationaux.", b2c_price: "24€", b2c_period: "/mois", b2c_trial: "Essai gratuit 3 jours", b2c_f1: "Communication multilingue", b2c_f2: "Jusqu'à 5 participants", b2c_f3: "Sous-titres et transcription", biz_badge: "Recommandé", biz_title: "Business", biz_desc: "Pour les équipes avancées.", biz_price: "99€", biz_period: "/mois par équipe", biz_trial: "Essai gratuit 3 jours", biz_f1: "Jusqu'à 50 participants", biz_f2: "Jusqu'à 25 utilisateurs", biz_f3: "Gestion centralisée", biz_f4: "Support prioritaire", ent_title: "Enterprise / B2G", ent_desc: "Déploiement sur-mesure.", ent_price: "Sur-mesure", ent_contact: "Contacter les ventes", ent_f1: "Langues illimitées", ent_f2: "Cloud privé", ent_f3: "SLA dédié", ent_f4: "Formation et support" },
  contact: { back: "Retour aux offres", title: "Contacter les ventes", sub: "Pour les déploiements Enterprise et B2G. Notre équipe vous répond sous 24h.", email_label: "Email professionnel", email_placeholder: "nom@entreprise.com", project_label: "Votre projet", project_placeholder: "Décrivez votre besoin...", submit: "Envoyer la demande", err_invalid: "Format d'email invalide.", err_free: "Veuillez utiliser un email d'entreprise." }
};

const en = {
  nav: { prod: "Platform", ai: "AI", price: "Pricing", contact: "Contact", login: "Sign In", start: "Start Meeting" },
  hero: { badge: "Next-generation infrastructure", t1: "Global communication.", t2: "No language barriers.", sub: "The SaaS platform that lets your teams understand each other instantly. Everyone speaks their native language.", cta1: "Start a meeting", cta2: "Explore platform" },
  social: { title: "Built for international standards", m1_val: "5.5B", m1_lbl: "non-English speakers", m2_val: "1080p", m2_lbl: "Native HD video quality", m3_val: "50ms", m3_lbl: "Guaranteed global latency", m4_val: "E2EE", m4_lbl: "End-to-end encryption" },
  problem: { tag: "The Global Challenge", title: "Language barriers destroy productivity.", desc: "Business is global, but communication is not. Companies lose critical time to misunderstandings.", p1: "Unified HD Video", p2: "Instant Voice Translation", p3: "Security & Sovereignty" },
  ai: { title: "Power your meetings with AI.", sub: "Make the most of every call. Artificial intelligence documents and optimizes your discussions.", f1_title: "Live Note-taking", f1_desc: "AI writes minutes, identifies decisions, and assigns tasks.", f2_title: "Automated Summary", f2_desc: "A translated summary is emailed to all participants.", f3_title: "Studio Enhancement", f3_desc: "Noise cancellation and embedded translated subtitles." },
  integrations: { title: "Integrates perfectly with your ecosystem" },
  segments: { b2b_title: "Enterprise (B2B)", b2b_desc: "Unify your global communication and reduce infrastructure costs.", b2b_cta: "View team plans →", b2g_title: "Institutions (B2G)", b2g_desc: "Data sovereignty, custom deployment, and strict compliance.", b2g_cta: "Contact sales →", b2c_title: "Users (B2C)", b2c_desc: "Collaborate with foreign clients without language friction.", b2c_cta: "Start for free →" },
  final: { title: "Ready to transform your meetings?", cta1: "Start a meeting", cta2: "Contact the team" },
  pricing: { title: "Invest in clarity.", sub: "Deploy the most advanced infrastructure. Try for free for 3 days.", b2c_title: "Premium", b2c_desc: "For international freelancers.", b2c_price: "€24", b2c_period: "/month", b2c_trial: "Start 3-day free trial", b2c_f1: "Multilingual communication", b2c_f2: "Up to 5 participants", b2c_f3: "Subtitles and transcription", biz_badge: "Recommended", biz_title: "Business", biz_desc: "For advanced teams.", biz_price: "€99", biz_period: "/month per team", biz_trial: "Start 3-day free trial", biz_f1: "Up to 50 participants", biz_f2: "Up to 25 users", biz_f3: "Centralized management", biz_f4: "Priority support", ent_title: "Enterprise / B2G", ent_desc: "Custom deployment.", ent_price: "Custom", ent_contact: "Contact Sales", ent_f1: "Unlimited languages", ent_f2: "Private cloud", ent_f3: "Dedicated SLA", ent_f4: "Training and support" },
  contact: { back: "Back to pricing", title: "Contact Sales", sub: "For Enterprise and B2G deployments. We reply within 24h.", email_label: "Work Email", email_placeholder: "name@company.com", project_label: "Your Project", project_placeholder: "Describe your needs...", submit: "Send Request", err_invalid: "Invalid email format.", err_free: "Please use a corporate email address." }
};

const es = {
  nav: { prod: "Plataforma", ai: "IA", price: "Precios", contact: "Contacto", login: "Iniciar sesión", start: "Crear reunión" },
  hero: { badge: "Infraestructura de nueva generación", t1: "Comunicación global.", t2: "Sin barreras lingüísticas.", sub: "La plataforma SaaS que permite a sus equipos entenderse al instante. Cada uno habla su idioma materno.", cta1: "Iniciar reunión", cta2: "Explorar la plataforma" },
  social: { title: "Diseñado para estándares internacionales", m1_val: "5.500 M", m1_lbl: "de no angloparlantes", m2_val: "1080p", m2_lbl: "Calidad de vídeo HD nativa", m3_val: "50ms", m3_lbl: "Latencia global garantizada", m4_val: "E2EE", m4_lbl: "Cifrado de extremo a extremo" },
  problem: { tag: "El Desafío Global", title: "La barrera lingüística destruye la productividad.", desc: "Los negocios son globales, pero la comunicación no lo es. Las empresas pierden tiempo crítico debido a malentendidos.", p1: "Videoconferencia unificada HD", p2: "Traducción de voz instantánea", p3: "Seguridad y soberanía" },
  ai: { title: "Ponga la IA al servicio de sus reuniones.", sub: "Aproveche al máximo cada llamada. La inteligencia artificial documenta y optimiza sus discusiones.", f1_title: "Toma de notas en directo", f1_desc: "La IA redacta actas, identifica decisiones y asigna tareas.", f2_title: "Resumen automatizado", f2_desc: "Se envía automáticamente un resumen traducido por correo a todos los participantes.", f3_title: "Calidad de Estudio", f3_desc: "Supresión de ruido y subtítulos traducidos incrustados." },
  integrations: { title: "Se integra perfectamente con su ecosistema" },
  segments: { b2b_title: "Empresas (B2B)", b2b_desc: "Unifique su comunicación global y reduzca sus costos de infraestructura.", b2b_cta: "Ver planes para equipos →", b2g_title: "Instituciones (B2G)", b2g_desc: "Soberanía de datos, implementación a medida y cumplimiento estricto.", b2g_cta: "Contactar a ventas →", b2c_title: "Usuarios (B2C)", b2c_desc: "Colabore con clientes extranjeros sin ninguna fricción lingüística.", b2c_cta: "Empezar gratis →" },
  final: { title: "¿Listo para transformar sus reuniones?", cta1: "Crear una reunión", cta2: "Contactar al equipo" },
  pricing: { title: "Invierta en la claridad.", sub: "Implemente la infraestructura más avanzada. Pruebe gratis durante 3 días.", b2c_title: "Premium", b2c_desc: "Para autónomos internacionales.", b2c_price: "24€", b2c_period: "/mes", b2c_trial: "Prueba gratuita de 3 días", b2c_f1: "Comunicación multilingüe", b2c_f2: "Hasta 5 participantes", b2c_f3: "Subtítulos y transcripción", biz_badge: "Recomendado", biz_title: "Business", biz_desc: "Para equipos avanzados.", biz_price: "99€", biz_period: "/mes por equipo", biz_trial: "Prueba gratuita de 3 días", biz_f1: "Hasta 50 participantes", biz_f2: "Hasta 25 usuarios", biz_f3: "Gestión centralizada", biz_f4: "Soporte prioritario", ent_title: "Enterprise / B2G", ent_desc: "Implementación a medida.", ent_price: "A medida", ent_contact: "Contactar a ventas", ent_f1: "Idiomas ilimitados", ent_f2: "Nube privada", ent_f3: "SLA dedicado", ent_f4: "Formación y soporte" },
  contact: { back: "Volver a las ofertas", title: "Contactar a ventas", sub: "Para implementaciones Enterprise y B2G. Nuestro equipo responderá en 24h.", email_label: "Correo corporativo", email_placeholder: "nombre@empresa.com", project_label: "Su proyecto", project_placeholder: "Describa su necesidad...", submit: "Enviar solicitud", err_invalid: "Formato de correo no válido.", err_free: "Por favor, utilice un correo corporativo." }
};

const de = {
  nav: { prod: "Plattform", ai: "KI", price: "Preise", contact: "Kontakt", login: "Anmelden", start: "Meeting starten" },
  hero: { badge: "Infrastruktur der nächsten Generation", t1: "Globale Kommunikation.", t2: "Ohne Sprachbarrieren.", sub: "Die SaaS-Plattform, mit der sich Ihre Teams sofort verstehen. Jeder spricht seine Muttersprache.", cta1: "Meeting starten", cta2: "Angebote entdecken" },
  social: { title: "Gebaut für internationale Standards", m1_val: "5,5 Mrd.", m1_lbl: "Nicht-Englischsprachige", m2_val: "1080p", m2_lbl: "Native HD-Videoqualität", m3_val: "50ms", m3_lbl: "Garantierte globale Latenz", m4_val: "E2EE", m4_lbl: "Ende-zu-Ende-Verschlüsselung" },
  problem: { tag: "Die globale Herausforderung", title: "Sprachbarrieren zerstören die Produktivität.", desc: "Geschäfte sind global, Kommunikation jedoch nicht. Unternehmen verlieren kritische Zeit durch Missverständnisse.", p1: "Unified HD Videokonferenzen", p2: "Sofortige Sprachübersetzung", p3: "Sicherheit und Souveränität" },
  ai: { title: "Setzen Sie KI für Ihre Meetings ein.", sub: "Schöpfen Sie jeden Anruf voll aus. Künstliche Intelligenz dokumentiert und optimiert Ihre Gespräche.", f1_title: "Live-Notizen", f1_desc: "Die KI schreibt mit, identifiziert Entscheidungen und weist Aufgaben zu.", f2_title: "Automatisierte Zusammenfassung", f2_desc: "Eine übersetzte Zusammenfassung wird per E-Mail an alle gesendet.", f3_title: "Studio-Verbesserung", f3_desc: "Geräuschunterdrückung und eingebettete übersetzte Untertitel." },
  integrations: { title: "Fügt sich nahtlos in Ihr Ökosystem ein" },
  segments: { b2b_title: "Unternehmen (B2B)", b2b_desc: "Vereinheitlichen Sie Ihre globale Kommunikation und senken Sie Infrastrukturkosten.", b2b_cta: "Team-Pläne ansehen →", b2g_title: "Behörden (B2G)", b2g_desc: "Datensouveränität, maßgeschneiderte Bereitstellung und strenge Compliance.", b2g_cta: "Vertrieb kontaktieren →", b2c_title: "Nutzer (B2C)", b2c_desc: "Arbeiten Sie mit ausländischen Kunden ohne Sprachreibung zusammen.", b2c_cta: "Kostenlos starten →" },
  final: { title: "Bereit, Ihre Meetings zu transformieren?", cta1: "Meeting starten", cta2: "Team kontaktieren" },
  pricing: { title: "Investieren Sie in Klarheit.", sub: "Stellen Sie die fortschrittlichste Infrastruktur bereit. 3 Tage kostenlos testen.", b2c_title: "Premium", b2c_desc: "Für internationale Freiberufler.", b2c_price: "24€", b2c_period: "/Monat", b2c_trial: "3 Tage kostenlos testen", b2c_f1: "Mehrsprachige Kommunikation", b2c_f2: "Bis zu 5 Teilnehmer", b2c_f3: "Untertitel und Transkription", biz_badge: "Empfohlen", biz_title: "Business", biz_desc: "Für fortgeschrittene Teams.", biz_price: "99€", biz_period: "/Monat pro Team", biz_trial: "3 Tage kostenlos testen", biz_f1: "Bis zu 50 Teilnehmer", biz_f2: "Bis zu 25 Nutzer", biz_f3: "Zentrale Verwaltung", biz_f4: "Prioritäts-Support", ent_title: "Enterprise / B2G", ent_desc: "Maßgeschneiderte Bereitstellung.", ent_price: "Nach Maß", ent_contact: "Vertrieb kontaktieren", ent_f1: "Unbegrenzte Sprachen", ent_f2: "Private Cloud", ent_f3: "Dediziertes SLA", ent_f4: "Schulung und Support" },
  contact: { back: "Zurück zu den Angeboten", title: "Vertrieb kontaktieren", sub: "Für Enterprise- und B2G-Bereitstellungen. Unser Team antwortet innerhalb von 24h.", email_label: "Geschäftliche E-Mail", email_placeholder: "name@unternehmen.de", project_label: "Ihr Projekt", project_placeholder: "Beschreiben Sie Ihren Bedarf...", submit: "Anfrage senden", err_invalid: "Ungültiges E-Mail-Format.", err_free: "Bitte verwenden Sie eine geschäftliche E-Mail." }
};

const it = {
  nav: { prod: "Piattaforma", ai: "IA", price: "Prezzi", contact: "Contatti", login: "Accedi", start: "Crea riunione" },
  hero: { badge: "Infrastruttura di nuova generazione", t1: "Comunicazione globale.", t2: "Senza barriere linguistiche.", sub: "La piattaforma SaaS che permette ai tuoi team di capirsi istantaneamente. Ognuno parla la propria lingua.", cta1: "Crea riunione", cta2: "Scopri le offerte" },
  social: { title: "Progettato per standard internazionali", m1_val: "5.5 Mld", m1_lbl: "di non anglofoni", m2_val: "1080p", m2_lbl: "Qualità video HD nativa", m3_val: "50ms", m3_lbl: "Latenza globale garantita", m4_val: "E2EE", m4_lbl: "Crittografia end-to-end" },
  problem: { tag: "La sfida globale", title: "La barriera linguistica distrugge la produttività.", desc: "Il business è globale, ma la comunicazione non lo è. Le aziende perdono tempo critico in incomprensioni.", p1: "Videoconferenza HD unificata", p2: "Traduzione vocale istantanea", p3: "Sicurezza e sovranità" },
  ai: { title: "Metti la potenza dell'IA al servizio delle tue riunioni.", sub: "Sfrutta al massimo ogni chiamata. L'intelligenza artificiale documenta e ottimizza le tue conversazioni.", f1_title: "Presa di appunti in tempo reale", f1_desc: "L'IA redige i verbali, identifica le decisioni e assegna i compiti.", f2_title: "Riassunto automatizzato", f2_desc: "Un riassunto tradotto viene inviato via email a tutti i partecipanti.", f3_title: "Miglioramento Studio", f3_desc: "Soppressione del rumore e sottotitoli tradotti integrati." },
  integrations: { title: "Si integra perfettamente nel tuo ecosistema" },
  segments: { b2b_title: "Aziende (B2B)", b2b_desc: "Unifica la tua comunicazione globale e riduci i costi dell'infrastruttura.", b2b_cta: "Vedi i piani per i team →", b2g_title: "Istituzioni (B2G)", b2g_desc: "Sovranità dei dati, implementazione su misura e conformità rigorosa.", b2g_cta: "Contatta le vendite →", b2c_title: "Utenti (B2C)", b2c_desc: "Collabora con i tuoi clienti stranieri senza alcun attrito linguistico.", b2c_cta: "Inizia gratuitamente →" },
  final: { title: "Pronto a trasformare le tue riunioni?", cta1: "Crea una riunione", cta2: "Contatta il team" },
  pricing: { title: "Investi nella chiarezza.", sub: "Implementa l'infrastruttura più avanzata. Prova gratuitamente per 3 giorni.", b2c_title: "Premium", b2c_desc: "Per i freelance internazionali.", b2c_price: "24€", b2c_period: "/mese", b2c_trial: "Prova gratuita di 3 giorni", b2c_f1: "Comunicazione multilingue", b2c_f2: "Fino a 5 partecipanti", b2c_f3: "Sottotitoli e trascrizione", biz_badge: "Consigliato", biz_title: "Business", biz_desc: "Per team avanzati.", biz_price: "99€", biz_period: "/mese per team", biz_trial: "Prova gratuita di 3 giorni", biz_f1: "Fino a 50 partecipanti", biz_f2: "Fino a 25 utenti", biz_f3: "Gestione centralizzata", biz_f4: "Supporto prioritario", ent_title: "Enterprise / B2G", ent_desc: "Implementazione su misura.", ent_price: "Su misura", ent_contact: "Contatta le vendite", ent_f1: "Lingue illimitate", ent_f2: "Cloud privato", ent_f3: "SLA dedicato", ent_f4: "Formazione e supporto" },
  contact: { back: "Torna alle offerte", title: "Contatta le vendite", sub: "Per implementazioni Enterprise e B2G. Il nostro team risponderà entro 24 ore.", email_label: "Email professionale", email_placeholder: "nome@azienda.it", project_label: "Il tuo progetto", project_placeholder: "Descrivi le tue esigenze...", submit: "Invia richiesta", err_invalid: "Formato email non valido.", err_free: "Si prega di utilizzare un'email aziendale." }
};

const pt = {
  nav: { prod: "Plataforma", ai: "IA", price: "Preços", contact: "Contato", login: "Entrar", start: "Criar reunião" },
  hero: { badge: "Infraestrutura de nova geração", t1: "Comunicação global.", t2: "Sem barreiras linguísticas.", sub: "A plataforma SaaS que permite que suas equipes se entendam instantaneamente. Cada um fala sua língua.", cta1: "Criar reunião", cta2: "Descobrir ofertas" },
  social: { title: "Construído para padrões internacionais", m1_val: "5.5 Bilhões", m1_lbl: "de não anglófonos", m2_val: "1080p", m2_lbl: "Qualidade de vídeo HD nativa", m3_val: "50ms", m3_lbl: "Latência global garantida", m4_val: "E2EE", m4_lbl: "Criptografia de ponta a ponta" },
  problem: { tag: "O desafio global", title: "A barreira linguística destrói a produtividade.", desc: "Os negócios são globais, mas a comunicação não é. As empresas perdem tempo crítico devido a mal-entendidos.", p1: "Videoconferência unificada HD", p2: "Tradução de voz instantânea", p3: "Segurança e soberania" },
  ai: { title: "Coloque a força da IA a serviço das suas reuniões.", sub: "Aproveite ao máximo cada chamada. A inteligência artificial documenta e otimiza suas conversas.", f1_title: "Anotações automáticas", f1_desc: "A IA redige as atas, identifica decisões e atribui tarefas.", f2_title: "Resumo automatizado", f2_desc: "Um resumo traduzido é enviado por e-mail a todos os participantes.", f3_title: "Aprimoramento Studio", f3_desc: "Supressão de ruído e legendas traduzidas incorporadas." },
  integrations: { title: "Integra-se perfeitamente ao seu ecossistema" },
  segments: { b2b_title: "Empresas (B2B)", b2b_desc: "Unifique sua comunicação global e reduza custos de infraestrutura.", b2b_cta: "Ver planos de equipe →", b2g_title: "Instituições (B2G)", b2g_desc: "Soberania de dados, implantação sob medida e conformidade rigorosa.", b2g_cta: "Contatar vendas →", b2c_title: "Usuários (B2C)", b2c_desc: "Colabore com clientes estrangeiros sem atrito linguístico.", b2c_cta: "Começar grátis →" },
  final: { title: "Pronto para transformar suas reuniões?", cta1: "Criar reunião", cta2: "Contatar a equipe" },
  pricing: { title: "Invista na clareza.", sub: "Implemente a infraestrutura mais avançada. Teste grátis por 3 dias.", b2c_title: "Premium", b2c_desc: "Para freelancers internacionais.", b2c_price: "24€", b2c_period: "/mês", b2c_trial: "Teste grátis de 3 dias", b2c_f1: "Comunicação multilíngue", b2c_f2: "Até 5 participantes", b2c_f3: "Legendas e transcrição", biz_badge: "Recomendado", biz_title: "Business", biz_desc: "Para equipes avançadas.", biz_price: "99€", biz_period: "/mês por equipe", biz_trial: "Teste grátis de 3 dias", biz_f1: "Até 50 participantes", biz_f2: "Até 25 usuários", biz_f3: "Gestão centralizada", biz_f4: "Suporte prioritário", ent_title: "Enterprise / B2G", ent_desc: "Implantação sob medida.", ent_price: "Sob medida", ent_contact: "Contatar vendas", ent_f1: "Idiomas ilimitados", ent_f2: "Cloud privado", ent_f3: "SLA dedicado", ent_f4: "Treinamento e suporte" },
  contact: { back: "Voltar às ofertas", title: "Contatar Vendas", sub: "Para implantações Enterprise e B2G. Nossa equipe responderá em 24h.", email_label: "E-mail profissional", email_placeholder: "nome@empresa.com", project_label: "Seu projeto", project_placeholder: "Descreva sua necessidade...", submit: "Enviar solicitação", err_invalid: "Formato de e-mail inválido.", err_free: "Use um e-mail corporativo." }
};

const nl = {
  nav: { prod: "Platform", ai: "AI", price: "Tarieven", contact: "Contact", login: "Inloggen", start: "Vergadering starten" },
  hero: { badge: "Infrastructuur van de volgende generatie", t1: "Wereldwijde communicatie.", t2: "Zonder taalbarrières.", sub: "Het SaaS-platform waarmee uw teams elkaar direct begrijpen. Iedereen spreekt zijn moedertaal.", cta1: "Vergadering starten", cta2: "Aanbiedingen ontdekken" },
  social: { title: "Gebouwd voor internationale standaarden", m1_val: "5.5 Mld", m1_lbl: "niet-Engelstaligen", m2_val: "1080p", m2_lbl: "Native HD videokwaliteit", m3_val: "50ms", m3_lbl: "Gegarandeerde wereldwijde latentie", m4_val: "E2EE", m4_lbl: "End-to-end encryptie" },
  problem: { tag: "De wereldwijde uitdaging", title: "De taalbarrière vernietigt de productiviteit.", desc: "Zakendoen is wereldwijd, maar communicatie is dat niet. Bedrijven verliezen kritieke tijd door misverstanden.", p1: "Geünificeerde HD videoconferentie", p2: "Directe stemvertaling", p3: "Veiligheid en soevereiniteit" },
  ai: { title: "Zet de kracht van AI in voor uw vergaderingen.", sub: "Benut elk gesprek ten volle. Kunstmatige intelligentie documenteert en optimaliseert uw uitwisselingen.", f1_title: "Live aantekeningen", f1_desc: "De AI schrijft notulen, identificeert beslissingen en wijst taken toe.", f2_title: "Geautomatiseerde samenvatting", f2_desc: "Een vertaalde samenvatting wordt per e-mail naar alle deelnemers gestuurd.", f3_title: "Studio Verbetering", f3_desc: "Ruisonderdrukking en ingebedde vertaalde ondertitels." },
  integrations: { title: "Integreert perfect in uw ecosysteem" },
  segments: { b2b_title: "Bedrijven (B2B)", b2b_desc: "Verenig uw wereldwijde communicatie en verlaag infrastructuurkosten.", b2b_cta: "Teamplannen bekijken →", b2g_title: "Instellingen (B2G)", b2g_desc: "Datasoevereiniteit, implementatie op maat en strikte naleving.", b2g_cta: "Contact opnemen met sales →", b2c_title: "Gebruikers (B2C)", b2c_desc: "Werk samen met buitenlandse klanten zonder taalwrijving.", b2c_cta: "Gratis starten →" },
  final: { title: "Klaar om uw vergaderingen te transformeren?", cta1: "Vergadering starten", cta2: "Contact opnemen met het team" },
  pricing: { title: "Investeer in helderheid.", sub: "Implementeer de meest geavanceerde infrastructuur. Probeer 3 dagen gratis.", b2c_title: "Premium", b2c_desc: "Voor internationale freelancers.", b2c_price: "24€", b2c_period: "/maand", b2c_trial: "3 dagen gratis proberen", b2c_f1: "Meertalige communicatie", b2c_f2: "Tot 5 deelnemers", b2c_f3: "Ondertiteling en transcriptie", biz_badge: "Aanbevolen", biz_title: "Business", biz_desc: "Voor geavanceerde teams.", biz_price: "99€", biz_period: "/maand per team", biz_trial: "3 dagen gratis proberen", biz_f1: "Tot 50 deelnemers", biz_f2: "Tot 25 gebruikers", biz_f3: "Gecentraliseerd beheer", biz_f4: "Prioriteitsondersteuning", ent_title: "Enterprise / B2G", ent_desc: "Implementatie op maat.", ent_price: "Op maat", ent_contact: "Contact opnemen met sales", ent_f1: "Onbeperkte talen", ent_f2: "Private cloud", ent_f3: "Toegewijde SLA", ent_f4: "Training en ondersteuning" },
  contact: { back: "Terug naar aanbiedingen", title: "Neem contact op met sales", sub: "Voor Enterprise en B2G implementaties. Ons team reageert binnen 24 uur.", email_label: "Zakelijk e-mailadres", email_placeholder: "naam@bedrijf.nl", project_label: "Uw project", project_placeholder: "Beschrijf uw behoefte...", submit: "Aanvraag verzenden", err_invalid: "Ongeldig e-mailformaat.", err_free: "Gebruik een zakelijk e-mailadres." }
};

const zh = {
  nav: { prod: "平台", ai: "人工智能", price: "定价", contact: "联系我们", login: "登录", start: "发起会议" },
  hero: { badge: "下一代视频基础设施", t1: "全球沟通。", t2: "打破语言障碍。", sub: "专为国际团队设计的智能视频会议SaaS平台，让每个人都能用母语自然交流。", cta1: "发起会议", cta2: "探索平台" },
  social: { title: "为国际标准而建", m1_val: "55亿", m1_lbl: "非英语母语者", m2_val: "1080p", m2_lbl: "原生高清画质", m3_val: "50ms", m3_lbl: "全球超低延迟保证", m4_val: "E2EE", m4_lbl: "端到端加密" },
  problem: { tag: "全球挑战", title: "语言障碍正在摧毁生产力。", desc: "商业是全球化的，但沟通却不是。企业因沟通误解而损失了大量宝贵时间。", p1: "统一高清视频会议", p2: "即时语音翻译", p3: "数据安全与主权" },
  ai: { title: "让AI为您的会议服务。", sub: "充分利用每一次通话。人工智能自动记录并优化您的交流。", f1_title: "实时自动做笔记", f1_desc: "AI自动生成会议纪要，提取关键决策并分配任务。", f2_title: "自动化会议摘要", f2_desc: "会议结束后，自动向所有与会者发送翻译好的结构化摘要。", f3_title: "工作室级提升", f3_desc: "动态降噪和嵌入式翻译字幕。" },
  integrations: { title: "完美融入您的生态系统" },
  segments: { b2b_title: "企业 (B2B)", b2b_desc: "统一全球沟通并降低基础设施成本。", b2b_cta: "查看团队计划 →", b2g_title: "机构 (B2G)", b2g_desc: "数据主权、定制部署和严格合规。", b2g_cta: "联系销售 →", b2c_title: "用户 (B2C)", b2c_desc: "毫无语言摩擦地与外国客户协作。", b2c_cta: "免费开始 →" },
  final: { title: "准备好改变您的会议了吗？", cta1: "发起会议", cta2: "联系团队" },
  pricing: { title: "投资于清晰的沟通。", sub: "部署最先进的基础设施。免费试用3天。", b2c_title: "个人高级版", b2c_desc: "适合国际自由职业者。", b2c_price: "24€", b2c_period: "/月", b2c_trial: "免费试用3天", b2c_f1: "多语言交流", b2c_f2: "最多5名参与者", b2c_f3: "字幕和转录", biz_badge: "推荐", biz_title: "商业版", biz_desc: "适合需要高级协作的团队。", biz_price: "99€", biz_period: "/月/团队", biz_trial: "免费试用3天", biz_f1: "最多50名参与者", biz_f2: "最多25名用户", biz_f3: "集中管理", biz_f4: "优先支持", ent_title: "企业/政府", ent_desc: "定制化部署。", ent_price: "定制", ent_contact: "联系销售", ent_f1: "无限语言", ent_f2: "私有云部署", ent_f3: "专属SLA", ent_f4: "培训和支持" },
  contact: { back: "返回定价", title: "联系销售", sub: "填写此表单以了解企业部署方案。我们将于24小时内回复。", email_label: "工作邮箱", email_placeholder: "name@company.com", project_label: "项目详情", project_placeholder: "描述您的需求...", submit: "发送请求", err_invalid: "邮箱格式无效。", err_free: "请使用企业邮箱地址。" }
};

const ja = {
  nav: { prod: "プラットフォーム", ai: "AI", price: "料金", contact: "お問い合わせ", login: "ログイン", start: "会議を開始" },
  hero: { badge: "次世代インフラストラクチャ", t1: "グローバルなコミュニケーション。", t2: "言語の壁なしで。", sub: "チームが瞬時に理解し合えるSaaSプラットフォーム。誰もが母国語で話せます。", cta1: "会議を開始", cta2: "プラットフォームを探索" },
  social: { title: "国際標準向けに構築", m1_val: "55億人", m1_lbl: "の非英語圏ユーザー", m2_val: "1080p", m2_lbl: "ネイティブHDビデオ品質", m3_val: "50ms", m3_lbl: "保証されたグローバルレイテンシ", m4_val: "E2EE", m4_lbl: "エンドツーエンド暗号化" },
  problem: { tag: "グローバルな課題", title: "言語の壁が生産性を破壊する。", desc: "ビジネスはグローバルですが、コミュニケーションはそうではありません。企業は誤解により重要な時間を失っています。", p1: "統合HDビデオ会議", p2: "リアルタイム音声翻訳", p3: "セキュリティと主権" },
  ai: { title: "会議にAIを活用する。", sub: "すべての通話を最大限に活用します。人工知能が会話を記録し、最適化します。", f1_title: "ライブ自動議事録", f1_desc: "AIが議事録を作成し、重要な決定を抽出し、タスクを割り当てます。", f2_title: "自動化された要約", f2_desc: "翻訳された要約が全参加者にメールで送信されます。", f3_title: "スタジオ品質", f3_desc: "動的なノイズキャンセリングと埋め込み翻訳字幕。" },
  integrations: { title: "エコシステムと完全に統合" },
  segments: { b2b_title: "企業 (B2B)", b2b_desc: "グローバルなコミュニケーションを統合し、インフラコストを削減します。", b2b_cta: "チームプランを見る →", b2g_title: "機関 (B2G)", b2g_desc: "データ主権、カスタム展開、および厳格なコンプライアンス。", b2g_cta: "営業に連絡 →", b2c_title: "ユーザー (B2C)", b2c_desc: "言語の摩擦なしで海外のクライアントとコラボレーションします。", b2c_cta: "無料で開始 →" },
  final: { title: "会議を変革する準備はできましたか？", cta1: "会議を開始", cta2: "チームに連絡" },
  pricing: { title: "明確さに投資する。", sub: "最先端のインフラストラクチャを展開します。3日間無料でお試しください。", b2c_title: "プレミアム", b2c_desc: "国際的なフリーランサー向け。", b2c_price: "24€", b2c_period: "/月", b2c_trial: "3日間の無料トライアル", b2c_f1: "多言語コミュニケーション", b2c_f2: "最大5人の参加者", b2c_f3: "字幕と文字起こし", biz_badge: "推奨", biz_title: "ビジネス", biz_desc: "高度なチーム向け。", biz_price: "99€", biz_period: "/月（チーム）", biz_trial: "3日間の無料トライアル", biz_f1: "最大50人の参加者", biz_f2: "最大25ユーザー", biz_f3: "集中管理", biz_f4: "優先サポート", ent_title: "エンタープライズ / 機関", ent_desc: "カスタム展開。", ent_price: "カスタム", ent_contact: "営業に連絡", ent_f1: "無制限の言語", ent_f2: "プライベートクラウド", ent_f3: "専用SLA", ent_f4: "トレーニングとサポート" },
  contact: { back: "料金に戻る", title: "営業に連絡", sub: "エンタープライズの展開については、このフォームに記入してください。24時間以内に返信します。", email_label: "勤務先メール", email_placeholder: "name@company.com", project_label: "プロジェクトの詳細", project_placeholder: "要件を記述してください...", submit: "リクエストを送信", err_invalid: "無効なメール形式。", err_free: "会社のメールアドレスを使用してください。" }
};

const ar = {
  nav: { prod: "المنصة", ai: "الذكاء الاصطناعي", price: "الأسعار", contact: "اتصل بنا", login: "تسجيل الدخول", start: "بدء اجتماع" },
  hero: { badge: "بنية تحتية من الجيل القادم", t1: "تواصل عالمي.", t2: "بدون حواجز لغوية.", sub: "منصة SaaS التي تتيح لفرقك فهم بعضهم البعض على الفور. كل شخص يتحدث بلغته الأم.", cta1: "بدء اجتماع", cta2: "اكتشف العروض" },
  social: { title: "مصمم للمعايير الدولية", m1_val: "5.5 مليار", m1_lbl: "غير ناطقين بالإنجليزية", m2_val: "1080p", m2_lbl: "جودة فيديو HD أصلية", m3_val: "50ms", m3_lbl: "زمن وصول عالمي مضمون", m4_val: "E2EE", m4_lbl: "تشفير شامل" },
  problem: { tag: "التحدي العالمي", title: "حواجز اللغة تدمر الإنتاجية.", desc: "الأعمال عالمية، لكن التواصل ليس كذلك. تفقد الشركات وقتاً حرجاً بسبب سوء الفهم.", p1: "مؤتمرات فيديو موحدة HD", p2: "ترجمة صوتية فورية", p3: "الأمان والسيادة" },
  ai: { title: "ضع الذكاء الاصطناعي في خدمة اجتماعاتك.", sub: "استفد من كل مكالمة بالكامل. يقوم الذكاء الاصطناعي بتوثيق وتحسين محادثاتك.", f1_title: "تدوين آلي للملاحظات", f1_desc: "يكتب الذكاء الاصطناعي ويستخرج القرارات ويعين المهام.", f2_title: "ملخص آلي", f2_desc: "يتم إرسال ملخص مترجم عبر البريد الإلكتروني إلى جميع المشاركين.", f3_title: "جودة الاستوديو", f3_desc: "إلغاء الضوضاء وترجمات مدمجة." },
  integrations: { title: "يتكامل تمامًا مع نظامك البيئي" },
  segments: { b2b_title: "الشركات (B2B)", b2b_desc: "وحد اتصالاتك العالمية وقلل تكاليف البنية التحتية.", b2b_cta: "عرض خطط الفرق →", b2g_title: "المؤسسات (B2G)", b2g_desc: "سيادة البيانات، نشر مخصص وامتثال صارم.", b2g_cta: "اتصل بالمبيعات →", b2c_title: "المستخدمون (B2C)", b2c_desc: "تعاون مع عملائك الأجانب دون أي احتكاك لغوي.", b2c_cta: "ابدأ مجانًا →" },
  final: { title: "هل أنت مستعد لتحويل اجتماعاتك؟", cta1: "بدء اجتماع", cta2: "اتصل بالفريق" },
  pricing: { title: "استثمر في الوضوح.", sub: "انشر البنية التحتية الأكثر تقدمًا. جرب مجانًا لمدة 3 أيام.", b2c_title: "بريميوم", b2c_desc: "للمستقلين الدوليين.", b2c_price: "24€", b2c_period: "/شهر", b2c_trial: "تجربة مجانية لمدة 3 أيام", b2c_f1: "تواصل متعدد اللغات", b2c_f2: "حتى 5 مشاركين", b2c_f3: "ترجمات ونص مكتوب", biz_badge: "موصى به", biz_title: "أعمال", biz_desc: "للفرق المتقدمة.", biz_price: "99€", biz_period: "/شهر للفريق", biz_trial: "تجربة مجانية لمدة 3 أيام", biz_f1: "حتى 50 مشارك", biz_f2: "حتى 25 مستخدم", biz_f3: "إدارة مركزية", biz_f4: "دعم ذو أولوية", ent_title: "مؤسسات / شركات", ent_desc: "نشر مخصص.", ent_price: "مخصص", ent_contact: "اتصل بالمبيعات", ent_f1: "لغات غير محدودة", ent_f2: "سحابة خاصة", ent_f3: "SLA مخصص", ent_f4: "تدريب ودعم" },
  contact: { back: "العودة للعروض", title: "اتصل بالمبيعات", sub: "للنشر في الشركات. سنرد خلال 24 ساعة.", email_label: "بريد العمل", email_placeholder: "name@company.com", project_label: "مشروعك", project_placeholder: "صف احتياجاتك...", submit: "إرسال الطلب", err_invalid: "صيغة بريد غير صالحة.", err_free: "يرجى استخدام بريد شركة." }
};

export const translations = {
  fr, en, es, de, it, pt, nl, zh, ja, ar
};

export type LanguageCode = keyof typeof translations;